# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='autopilot/protobuf/cal.proto',
  package='',
  serialized_pb='\n\x1c\x61utopilot/protobuf/cal.proto\"Q\n\x07\x43\x61lData\x12\n\n\x02\x61x\x18\x01 \x02(\x02\x12\n\n\x02\x61y\x18\x02 \x02(\x02\x12\n\n\x02\x61z\x18\x03 \x02(\x02\x12\n\n\x02mx\x18\x04 \x02(\x02\x12\n\n\x02my\x18\x05 \x02(\x02\x12\n\n\x02mz\x18\x06 \x02(\x02')




_CALDATA = descriptor.Descriptor(
  name='CalData',
  full_name='CalData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ax', full_name='CalData.ax', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ay', full_name='CalData.ay', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='az', full_name='CalData.az', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mx', full_name='CalData.mx', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='my', full_name='CalData.my', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mz', full_name='CalData.mz', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=32,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['CalData'] = _CALDATA

class CalData(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CALDATA
  
  # @@protoc_insertion_point(class_scope:CalData)

# @@protoc_insertion_point(module_scope)
