# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='autopilot/protobuf/log_data.proto',
  package='',
  serialized_pb='\n!autopilot/protobuf/log_data.proto\"\x99\x01\n\x08log_data\x12\x1e\n\x05level\x18\x01 \x02(\x0e\x32\x0f.log_data.Level\x12\x0f\n\x07\x64\x65tails\x18\x02 \x02(\r\x12\x0c\n\x04\x66ile\x18\x03 \x02(\t\x12\x0c\n\x04line\x18\x04 \x02(\r\x12\x0f\n\x07message\x18\x05 \x02(\t\"/\n\x05Level\x12\x07\n\x03\x45RR\x10\x01\x12\x08\n\x04WARN\x10\x02\x12\x08\n\x04INFO\x10\x03\x12\t\n\x05\x44\x45\x42UG\x10\x04')



_LOG_DATA_LEVEL = descriptor.EnumDescriptor(
  name='Level',
  full_name='log_data.Level',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='ERR', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='WARN', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INFO', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DEBUG', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=144,
  serialized_end=191,
)


_LOG_DATA = descriptor.Descriptor(
  name='log_data',
  full_name='log_data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='level', full_name='log_data.level', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='details', full_name='log_data.details', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='file', full_name='log_data.file', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='line', full_name='log_data.line', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='log_data.message', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LOG_DATA_LEVEL,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=38,
  serialized_end=191,
)

_LOG_DATA.fields_by_name['level'].enum_type = _LOG_DATA_LEVEL
_LOG_DATA_LEVEL.containing_type = _LOG_DATA;
DESCRIPTOR.message_types_by_name['log_data'] = _LOG_DATA

class log_data(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOG_DATA
  
  # @@protoc_insertion_point(class_scope:log_data)

# @@protoc_insertion_point(module_scope)
