# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='autopilot/protobuf/pilot.proto',
  package='',
  serialized_pb='\n\x1e\x61utopilot/protobuf/pilot.proto\"2\n\x08\x43trlData\x12\x19\n\x05param\x18\x01 \x02(\x0e\x32\n.CtrlParam\x12\x0b\n\x03val\x18\x02 \x02(\x02\"\xdf\x01\n\x06Params\x12\x11\n\tstart_lon\x18\x01 \x02(\x01\x12\x11\n\tstart_lat\x18\x02 \x02(\x01\x12\x11\n\tstart_alt\x18\x03 \x02(\x01\x12\x0e\n\x06setp_x\x18\x04 \x02(\x02\x12\x0e\n\x06setp_y\x18\x05 \x02(\x02\x12\x0e\n\x06setp_z\x18\x06 \x02(\x02\x12\x15\n\rsetp_z_ground\x18\x07 \x01(\x02\x12\x10\n\x08setp_yaw\x18\x08 \x01(\x02\x12\x15\n\rsetp_speed_xy\x18\t \x02(\x02\x12\x14\n\x0csetp_speed_z\x18\n \x02(\x02\x12\x16\n\x0esetp_speed_yaw\x18\x0b \x02(\x02\"D\n\x08PilotReq\x12\x1a\n\x04type\x18\x01 \x02(\x0e\x32\x0c.RequestType\x12\x1c\n\tctrl_data\x18\x02 \x01(\x0b\x32\t.CtrlData\"M\n\x08PilotRep\x12\x17\n\x06status\x18\x01 \x02(\x0e\x32\x07.Status\x12\x0f\n\x07\x65rr_msg\x18\x02 \x01(\t\x12\x17\n\x06params\x18\x03 \x01(\x0b\x32\x07.Params*|\n\x0bRequestType\x12\x0f\n\x0bMODE_NORMAL\x10\x01\x12\x0c\n\x08MODE_CAL\x10\x02\x12\x0b\n\x07SPIN_UP\x10\x03\x12\r\n\tSPIN_DOWN\x10\x04\x12\x0e\n\nRESET_CTRL\x10\x05\x12\x0e\n\nGET_PARAMS\x10\x06\x12\x12\n\x0eSET_CTRL_PARAM\x10\x07*u\n\tCtrlParam\x12\t\n\x05POS_X\x10\x01\x12\t\n\x05POS_Y\x10\x02\x12\x10\n\x0cPOS_Z_GROUND\x10\x03\x12\t\n\x05POS_Z\x10\x04\x12\x0b\n\x07POS_YAW\x10\x05\x12\x0c\n\x08SPEED_XY\x10\x06\x12\x0b\n\x07SPEED_Z\x10\x07\x12\r\n\tSPEED_YAW\x10\x08*>\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\x0c\n\x08\x45_SYNTAX\x10\x01\x12\x0e\n\nE_SEMANTIC\x10\x02\x12\x0e\n\nE_HARDWARE\x10\x03')

_REQUESTTYPE = descriptor.EnumDescriptor(
  name='RequestType',
  full_name='RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='MODE_NORMAL', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MODE_CAL', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SPIN_UP', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SPIN_DOWN', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RESET_CTRL', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GET_PARAMS', index=5, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SET_CTRL_PARAM', index=6, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=461,
  serialized_end=585,
)


_CTRLPARAM = descriptor.EnumDescriptor(
  name='CtrlParam',
  full_name='CtrlParam',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='POS_X', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='POS_Y', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='POS_Z_GROUND', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='POS_Z', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='POS_YAW', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SPEED_XY', index=5, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SPEED_Z', index=6, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SPEED_YAW', index=7, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=587,
  serialized_end=704,
)


_STATUS = descriptor.EnumDescriptor(
  name='Status',
  full_name='Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='E_SYNTAX', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='E_SEMANTIC', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='E_HARDWARE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=706,
  serialized_end=768,
)


MODE_NORMAL = 1
MODE_CAL = 2
SPIN_UP = 3
SPIN_DOWN = 4
RESET_CTRL = 5
GET_PARAMS = 6
SET_CTRL_PARAM = 7
POS_X = 1
POS_Y = 2
POS_Z_GROUND = 3
POS_Z = 4
POS_YAW = 5
SPEED_XY = 6
SPEED_Z = 7
SPEED_YAW = 8
OK = 0
E_SYNTAX = 1
E_SEMANTIC = 2
E_HARDWARE = 3



_CTRLDATA = descriptor.Descriptor(
  name='CtrlData',
  full_name='CtrlData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='param', full_name='CtrlData.param', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='val', full_name='CtrlData.val', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=34,
  serialized_end=84,
)


_PARAMS = descriptor.Descriptor(
  name='Params',
  full_name='Params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='start_lon', full_name='Params.start_lon', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='start_lat', full_name='Params.start_lat', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='start_alt', full_name='Params.start_alt', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='setp_x', full_name='Params.setp_x', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='setp_y', full_name='Params.setp_y', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='setp_z', full_name='Params.setp_z', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='setp_z_ground', full_name='Params.setp_z_ground', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='setp_yaw', full_name='Params.setp_yaw', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='setp_speed_xy', full_name='Params.setp_speed_xy', index=8,
      number=9, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='setp_speed_z', full_name='Params.setp_speed_z', index=9,
      number=10, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='setp_speed_yaw', full_name='Params.setp_speed_yaw', index=10,
      number=11, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=87,
  serialized_end=310,
)


_PILOTREQ = descriptor.Descriptor(
  name='PilotReq',
  full_name='PilotReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='PilotReq.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ctrl_data', full_name='PilotReq.ctrl_data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=312,
  serialized_end=380,
)


_PILOTREP = descriptor.Descriptor(
  name='PilotRep',
  full_name='PilotRep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='status', full_name='PilotRep.status', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='err_msg', full_name='PilotRep.err_msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='params', full_name='PilotRep.params', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=382,
  serialized_end=459,
)

_CTRLDATA.fields_by_name['param'].enum_type = _CTRLPARAM
_PILOTREQ.fields_by_name['type'].enum_type = _REQUESTTYPE
_PILOTREQ.fields_by_name['ctrl_data'].message_type = _CTRLDATA
_PILOTREP.fields_by_name['status'].enum_type = _STATUS
_PILOTREP.fields_by_name['params'].message_type = _PARAMS
DESCRIPTOR.message_types_by_name['CtrlData'] = _CTRLDATA
DESCRIPTOR.message_types_by_name['Params'] = _PARAMS
DESCRIPTOR.message_types_by_name['PilotReq'] = _PILOTREQ
DESCRIPTOR.message_types_by_name['PilotRep'] = _PILOTREP

class CtrlData(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CTRLDATA
  
  # @@protoc_insertion_point(class_scope:CtrlData)

class Params(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PARAMS
  
  # @@protoc_insertion_point(class_scope:Params)

class PilotReq(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PILOTREQ
  
  # @@protoc_insertion_point(class_scope:PilotReq)

class PilotRep(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PILOTREP
  
  # @@protoc_insertion_point(class_scope:PilotRep)

# @@protoc_insertion_point(module_scope)
