# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='opcd/protobuf/opcd.proto',
  package='',
  serialized_pb='\n\x18opcd/protobuf/opcd.proto\"L\n\x05Value\x12\x0f\n\x07str_val\x18\x01 \x01(\t\x12\x0f\n\x07int_val\x18\x02 \x01(\x05\x12\x0f\n\x07\x64\x62l_val\x18\x03 \x01(\x01\x12\x10\n\x08\x62ool_val\x18\x04 \x01(\x08\"n\n\x07\x43trlReq\x12\x1b\n\x04type\x18\x01 \x02(\x0e\x32\r.CtrlReq.Type\x12\n\n\x02id\x18\x02 \x01(\t\x12\x13\n\x03val\x18\x03 \x01(\x0b\x32\x06.Value\"%\n\x04Type\x12\x07\n\x03GET\x10\x00\x12\x07\n\x03SET\x10\x01\x12\x0b\n\x07PERSIST\x10\x02\"\'\n\x04Pair\x12\n\n\x02id\x18\x01 \x02(\t\x12\x13\n\x03val\x18\x02 \x02(\x0b\x32\x06.Value\"\x98\x01\n\x07\x43trlRep\x12\x1f\n\x06status\x18\x01 \x02(\x0e\x32\x0f.CtrlRep.Status\x12\x14\n\x05pairs\x18\x02 \x03(\x0b\x32\x05.Pair\"V\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\x11\n\rPARAM_UNKNOWN\x10\x01\x12\x11\n\rTYPE_MISMATCH\x10\x02\x12\x10\n\x0cMALFORMED_ID\x10\x03\x12\x0c\n\x08IO_ERROR\x10\x04')



_CTRLREQ_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='CtrlReq.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='GET', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SET', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PERSIST', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=179,
  serialized_end=216,
)

_CTRLREP_STATUS = descriptor.EnumDescriptor(
  name='Status',
  full_name='CtrlRep.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PARAM_UNKNOWN', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_MISMATCH', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MALFORMED_ID', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='IO_ERROR', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=326,
  serialized_end=412,
)


_VALUE = descriptor.Descriptor(
  name='Value',
  full_name='Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='str_val', full_name='Value.str_val', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='int_val', full_name='Value.int_val', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dbl_val', full_name='Value.dbl_val', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bool_val', full_name='Value.bool_val', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=104,
)


_CTRLREQ = descriptor.Descriptor(
  name='CtrlReq',
  full_name='CtrlReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='CtrlReq.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id', full_name='CtrlReq.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='val', full_name='CtrlReq.val', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CTRLREQ_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=106,
  serialized_end=216,
)


_PAIR = descriptor.Descriptor(
  name='Pair',
  full_name='Pair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='Pair.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='val', full_name='Pair.val', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=218,
  serialized_end=257,
)


_CTRLREP = descriptor.Descriptor(
  name='CtrlRep',
  full_name='CtrlRep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='status', full_name='CtrlRep.status', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pairs', full_name='CtrlRep.pairs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CTRLREP_STATUS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=260,
  serialized_end=412,
)

_CTRLREQ.fields_by_name['type'].enum_type = _CTRLREQ_TYPE
_CTRLREQ.fields_by_name['val'].message_type = _VALUE
_CTRLREQ_TYPE.containing_type = _CTRLREQ;
_PAIR.fields_by_name['val'].message_type = _VALUE
_CTRLREP.fields_by_name['status'].enum_type = _CTRLREP_STATUS
_CTRLREP.fields_by_name['pairs'].message_type = _PAIR
_CTRLREP_STATUS.containing_type = _CTRLREP;
DESCRIPTOR.message_types_by_name['Value'] = _VALUE
DESCRIPTOR.message_types_by_name['CtrlReq'] = _CTRLREQ
DESCRIPTOR.message_types_by_name['Pair'] = _PAIR
DESCRIPTOR.message_types_by_name['CtrlRep'] = _CTRLREP

class Value(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VALUE
  
  # @@protoc_insertion_point(class_scope:Value)

class CtrlReq(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CTRLREQ
  
  # @@protoc_insertion_point(class_scope:CtrlReq)

class Pair(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PAIR
  
  # @@protoc_insertion_point(class_scope:Pair)

class CtrlRep(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CTRLREP
  
  # @@protoc_insertion_point(class_scope:CtrlRep)

# @@protoc_insertion_point(module_scope)
